name: CI
on: push

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd test && wget https://raw.githubusercontent.com/onqtam/doctest/master/doctest/doctest.h
      - run: mkdir -p build && cd build && cmake .. -DENABLE_TESTS=ON
      - run: cd build && make
      - run: ./bin/my_test
  codeQL:
    name: codeQL
    runs-on: ubuntu-latest
    steps:
      - uses: github/codeql-action/init@v1
      - with:
          languages:
            cpp
            # Here is where you build your code
            # - run: |
            # make bootstrap
            # make release
        run: cd build
        name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
