name: CI
on: push

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p build && cd build && cmake .. -DENABLE_TESTS=ON
      - run: pwd
      - run: make
      - run: ./bin/my_test
